{% set version = '1.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reshape2
  version: {{ version|replace("-", "_") }}

source:
  fn: reshape2_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/reshape2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reshape2/reshape2_{{ version }}.tar.gz
  sha256: 8aff94c935e75032344b52407593392ddd4e16a88bb206984340c816d42c710e

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, lattice, testthat (>= 0.8.0)
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-rcpp
    - r-plyr >=1.8.1
    - r-stringr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-plyr >=1.8.1
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('reshape2')"           # [not win]
    - "\"%R%\" -e \"library('reshape2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/reshape
  license: MIT + file LICENSE
  summary: 'Flexibly restructure and aggregate data using just two functions: melt and ''dcast''
    (or ''acast'').'

  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - lpantano
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: reshape2
# Title: Flexibly Reshape Data: A Reboot of the Reshape Package
# Version: 1.4.3
# Author: Hadley Wickham <h.wickham@gmail.com>
# Maintainer: Hadley Wickham <h.wickham@gmail.com>
# Description: Flexibly restructure and aggregate data using just two functions: melt and 'dcast' (or 'acast').
# License: MIT + file LICENSE
# URL: https://github.com/hadley/reshape
# BugReports: https://github.com/hadley/reshape/issues
# Depends: R (>= 3.1)
# Imports: plyr (>= 1.8.1), Rcpp, stringr
# Suggests: covr, lattice, testthat (>= 0.8.0)
# LinkingTo: Rcpp
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: yes
# Packaged: 2017-12-10 22:04:42 UTC; hadley
# Repository: CRAN
# Date/Publication: 2017-12-11 16:47:57 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
