travis:
  secure:
    BINSTAR_TOKEN: M+3yJnrw8vg4Hc22GhYi01Ppaazq2NjSiwWKg2P+ZNYFawac+8VV+LwfoFuwmLhtomBWpKbOv3ZGH0QT/lnDTGZ3WnMNfbbF0KgP34zE+cnJ4AL8GrY9oIHsoZ/axudC8ocqIylPvuFiBwvBPFKgZhumE5LIL89WfUL8E92Yt3Bb0D+olm5Cz7Q9Bc5F8JgCeeYZBAyxt02tHaVXoqXRbRe1yQDIn/UPbwDd6DKtZxAuMEKcGNPvE8dic36LG0eMoCKhc1cpH/6S1xKt1YLGL/WJNLDb05sODg0os3g3aUwCdlzHjaDm/I5P+4qpstJ0AXP0fjZckZfL2TN9fN9BoS1mFMSC0/fn7/Zh3SHH1vj+lsA6AhIZW/B2zJD+ouGxpjlRhZEtldeLBdtiqnK/K8EP5ZM6cMYzP8jB8OHmf9Y35ysgeUHiL4QAOWmeI/GiTyNGdS5EJ0sYDz6/foA07XD0k+ZtjGAHXfZETnaz9bYZk+kc1BkJHzugkYrGJD9IvXNn5lZGQtsPH0Ub2e5lOmZvviuIE/B8W7xFpZD2zC+7WsvvkqPUt+vroLk52a7l/ZtRCWrCRUEoBJyYAWPv/daWOx62yIXsp5pNK8p0kNKJM/TYmynL1Unny1dCUh0EpD9FGKF3Fsgaz/CfDij2HcPApPq6V2mfdHmmGOs8GBk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
