travis:
  secure:
    BINSTAR_TOKEN: IRo6TxeGhrVctThux7U+uHLjXRECM1RtFQ0FYq0H6OXneyVLSqhbiPScDVMuYHVNzRMPo8GQ0IzCFrc1cdrgCaCK9QsM4iiNLItt+jWUFmVEZ3g9VVqE4EUGCLHbjY0MbGsg21A8M+8dfiXDwC5XME2G/mn10g437MIJLEL6JfMB/bwCap79qI65LsrbVhtVxU8NGUMCW/dyydVrjih+jGa7Pv579xS3v9wGUAmcdkKa9G4RpAk/N5Er1V65ksL/Bk6RcMoUy5m5IZA7mTrWxjM+aAL6nctrTzLtU7yWlZnC47SIeUENls06qjyrXrN1AZ0d+jjImjgvPX9+Q8teBJIZ2/y1mU63Qa5V973WgnUryy7XvY3AEz1ljyuw3wGx9kPM4XyPPxW2dHZ99wuxtM4H9/xRi02y0o2Kr9yRPyPQppqJHfmTA/PkNKz1vrhLknBgTUPFM9VekmT3Z1K9GKSEDwHUHUA5kAvme6yTA9u3lAmO1vxLdK4DTk//AVzFe7QE/5lqbPuK0sxRs9mQoKg3z16mSd2KvBYYd2xYh29HvAISDxBSflQPk25vvhn058nvL4zcqTmWv6IYu0mQj2c9+nX+Y2llgpqB8VLLOU3ApV/N8jxkrxF3eMOz5Ckx/ZOUeh2f4Ht02nYu6iUnUdc8B2StftjenrU14v4kX4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
