travis:
  secure:
    BINSTAR_TOKEN: lPABJuLMYV+4zhBB9jUoxoiprhrC0ftOjamWaAA/9s/l9jt3MDBypuj3nOpkBWn5SQ6Q+gb2GRkfFecLu0Dw81dhW3qqRJv7mvds8sE0cuFtRcih1KApGOCAJmvyed0ABxAPXmEB1rlLWrQtpUKbtUbgJW9l27kiZuzBsartFzZQzD2s0zpbCTBGqIQIDCbhLzdq8FtYkUU6eDoLVM9n1VQBIVx6n7Ula5SzcjMP+usebj9d+ZCtD/SsCWm5KdxBc9WL3UwyHGtlnnSowHLouKOcfSInif7r+2H+zR/a7B5nb9ETWDZStyq8U9RH0oDfQ2eUxFM+aD6WZYH5IjdzzwOOzZSHW9fCCwt7P4rrvr/ZC65AWrWGZLDGT7LD3faTE1xV5vJuJsV9bAjEILYT3p5lbaiOG+XHms8Hwc/LUPxgsCejIhkvBZ8RYM/XfVc2/tc0EkR6nPdCs2CuCk+Pcyy2dD3fxRz6m4Dx1Dd5OlOg8YagCnbt1G5woa0ZpeeZm5EnDGN8e+/GZOiDqaXzm/Q0uTgMZg1QPlaiCOxrqpDrLIzwSdXngYJy4mc+dw25CF2ImDg/MAa4Ah0cAOFrmS8qJ20D6uERU/w3A9VhINEgZ83uFVjhfVpo8Cf3pV4biZZ/6GSSMye/StqbWUd6JIyND8+2G7pcg9c+OEEkm9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
